// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hgupbhqlpwcwtkwkwude.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhndXBiaHFscHdjd3Rrd2t3dWRlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY3OTI2OTMsImV4cCI6MjA2MjM2ODY5M30.eFCwO229-PZq_cs-yFeECuCGyNc9Fz0o2330pYgpSB4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);